In [1]:
# Import Libraries

In [2]:
import numpy as np
import pandas as pd

### 1. Import the moovies dataset

# https://www.kaggle.com/carolzhangdc/imdb-5000-movie-dataset

In [3]:
df=pd.read_csv('/Users/anak/Downloads/movie_metadata.csv')

In [4]:
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

### 2. Use crosstabs to show the number of moovies per country

In [6]:
pd.crosstab(df['country'],columns='count')

col_0                 count
country
Afghanistan               1
Argentina                 4
Aruba                     1
Australia                55
Bahamas                   1
...                     ...
Turkey                    1
UK                      448
USA                    3807
United Arab Emirates      1
West Germany              3

[65 rows x 1 columns]

### 3. Create a crosstab to show the number of films per director and genre splitted by country

In [58]:
pd.crosstab([df.director_name, df.genres],[df.country])

,country,Afghanistan,Argentina,Aruba,Australia,Bahamas,Belgium,Brazil,Bulgaria,Cambodia,Cameroon,...,Spain,Sweden,Switzerland,Taiwan,Thailand,Turkey,UK,USA,United Arab Emirates,West Germany
director_name,genres,,,,,,,,,,,,,,,,,,,,,
A. Raven Cruz,Action|Adventure|Comedy|Fantasy|Sci-Fi,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Aaron Hann,Drama|Horror|Mystery|Sci-Fi|Thriller,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Aaron Schneider,Drama|Mystery,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Aaron Seltzer,Comedy|Romance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Abel Ferrara,Crime|Drama,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zoran Lisinac,Comedy|Music|Romance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Álex de la Iglesia,Crime|Mystery|Thriller,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Émile Gaudreault,Comedy|Drama,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Éric Tessier,Action|Drama|Horror|Thriller,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Étienne Faure,Drama|Musical|Romance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### 4. Average duration of filmes grouped by color

In [55]:
pd.crosstab(df.color,"duration mean",df.duration,aggfunc='mean')

col_0             duration mean
color
 Black and White     112.253589
Color                107.042908

### 5. Average number of likes per director (assuming that total film's likes are counted as a sum of actor's likes)

In [57]:
pd.crosstab(df.director_name,'fblikes', df.actor_1_facebook_likes, aggfunc='sum')

col_0               fblikes
director_name
A. Raven Cruz         639.0
Aaron Hann            160.0
Aaron Schneider     13000.0
Aaron Seltzer        3000.0
Abel Ferrara          812.0
...                     ...
Zoran Lisinac         431.0
Álex de la Iglesia    439.0
Émile Gaudreault      636.0
Éric Tessier           50.0
Étienne Faure          19.0

[2398 rows x 1 columns]